name: Setup Virtual Container
description: >
  Set up a Linux container to use in workflow steps. Because the container is run inside a virtualized
  Alpine Linux distribution provided by jirutka/setup-alpine, the container can run on a different
  CPU architecture.
author: Sander Vocke

inputs:
  container:
    description: >
      URL of the container to use. It will be started using Podman.
    required: true
    default: null
  arch:
    description: >
      CPU architecture to use.
    default: x86_64

runs:
  using: composite
  steps:
    - name: Setup virtual container
      uses: jirutka/setup-alpine@v1
      with:
        arch: ${{ inputs.arch }}
        packages: podman findmnt
    - name: Start container process
      if: ${{ inputs.container }}
      shell: alpine.sh --root {0}
      run: |
         findmnt -l
         XDG_RUNTIME_DIR="" podman info --debug
         XDG_RUNTIME_DIR="" podman run ${{ inputs.container }}
    # - name: Start container process
    #   if: ${{ inputs.container }}
    #   uses: JarvusInnovations/background-action@v1
    #   with:
    #     run: alpine.sh <(podman run ${{ inputs.container }}) && touch container_started
    #     wait-on: container_started
    #     wait-for: 5m
    #     log-output: true
      
