name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:

  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Try
      uses: ./
      with:
        container: quay.io/pypa/manylinux_2_28_aarch64
        arch: aarch64
        podman_args: --privileged