name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        job:
          - arch: aarch64
            container: quay.io/pypa/manylinux_2_28_aarch64
        args:
          [ null, '--privileged' ]
          
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Try
      uses: ./
      with:
        container: ${{ matrix.job.container }}
        arch: ${{ matrix.job.arch }}
        podman_args: ${{ matrix.args }}